micronaut-projects/micronaut-build

src/main/groovy/io/micronaut/build/MicronautPublishingPlugin.groovy
- Correctly apply shadow configurations.
- Honour extra pom information from parent and bom projects
=> Changes to support micronaut-core

src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy
=> Add useJUnitPlatform if using Groovy 3

src/main/groovy/io/micronaut/build/MicronautDocsPlugin.groovy, src/main/groovy/io/micronaut/build/MicronautPublishingPlugin.groovy
=> Do not configure publish for doc/example projects

src/main/groovy/io/micronaut/build/MicronautPublishingPlugin.groovy
Fixes https://github.com/micronaut-projects/micronaut-core/issues/3816
=> Allow to opt-out of automatic Bintray publishing

.github/workflows/release.yml
https://github.com/gradle/wrapper-validation-action
﻿
=> add Gradle wrapper validation to workflow

src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy
=> Make sure `enforcedPlatform` is not used

src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy, src/main/groovy/io/micronaut/build/MicronautPublishingPlugin.groovy
=> Use resolved versions.

src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy, src/main/groovy/io/micronaut/build/MicronautPublishingPlugin.groovy
See https://github.com/orgs/micronaut-projects/teams/core-developers/discussions/108
=> Fix POM generation

src/main/template/css/main.css
Fixes issue mentioned [here](https://github.com/micronaut-projects/micronaut-core/issues/2553)
=> Fixes no-space white characters being added

src/main/groovy/io/micronaut/docs/ApiMacro.groovy, src/test/groovy/io/micronaut/docs/ApiMacroSpec.groovy
Close https://github.com/micronaut-projects/micronaut-build/issues/180
=> fix: broken ConfigurationProperties Nested links

build.gradle, src/main/java/io/micronaut/build/MicronautSharedSettingsPlugin.java
This commit enables capture of task inputs and adds common state
capture like the branch name, Git status, ...
=> Capture more data in build scans

build.gradle, src/main/groovy/io/micronaut/build/MicronautBasePlugin.groovy, src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy, src/main/groovy/io/micronaut/build/MicronautBuildExtension.groovy, src/main/groovy/io/micronaut/build/MicronautDependencyUpdatesPlugin.groovy, src/main/groovy/io/micronaut/build/MicronautModulePlugin.groovy
Builds on top of #205
See commit for details
=> Introduce a "module" plugin

build.gradle, src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy
This will let Gradle Enterprise detect flaky tests.
=> Add test retry plugin

src/main/java/io/micronaut/build/MicronautSharedSettingsPlugin.java
Publication of snapshots was driven by the root project version.
With the changes in 5.0.0, it's not always the case that the
root project had a version.
This commit fixes the problem by making sure that the project
version is set on all subprojects, including the root. This
makes use of the `projectVersion` property which is expected
to be found in `gradle.properties`. A sanity check was added
to make sure that this property is set when publishing.
In addition, there is now the ability to set a project group,
using the `projectGroup` property, which should make it
redundant to define a convention plugin which declares the
group and version.
=> Fix publication of snapshots

src/main/groovy/io/micronaut/build/MicronautBasePlugin.groovy, src/main/groovy/io/micronaut/build/MicronautDependencyResolutionConfigurationPlugin.groovy, src/main/groovy/io/micronaut/build/docs/JavadocAggregatorPlugin.java
This PR fixes a couple issues when generating javadocs with the new aggregation plugin.
=> Fix javadoc aggregation

src/main/java/io/micronaut/build/catalogs/MicronautVersionCatalogUpdatePlugin.java
On CI, we create PRs for dependency updates: this means we don't
want to generate a separate file, but instead we want to update
the current version catalog.
=> Fix version catalog update directory on CI

src/main/java/io/micronaut/build/MicronautSharedSettingsPlugin.java
We noted by accident that if the root project name has the same name
as a subproject, then docs generation will fail. To avoid this, this
commit adds a sanity check which will fail the build if we see such
a pattern.
=> Assert that project names are unique

src/main/groovy/io/micronaut/build/pom/PomFile.java, src/main/groovy/io/micronaut/build/pom/PomParser.groovy, src/test/groovy/io/micronaut/build/pom/PomParserTest.groovy
Fixes https://ge.micronaut.io/s/nu6vbyre3olyq/console-log
=> Fix POM parser not substituting properties in properties

src/main/groovy/io/micronaut/build/compat/MicronautBinaryCompatibilityPlugin.java
The previous fix wasn't working properly, as the computation of the
`baseline` property was still failing.
=> Properly fix dependency

src/main/groovy/io/micronaut/build/MicronautDocsPlugin.groovy, src/main/groovy/io/micronaut/build/docs/CreateReleasesDropdownTask.java, src/main/groovy/io/micronaut/docs/GitHubTagsParser.groovy, src/main/java/io/micronaut/build/JsonFetcher.java, src/test/groovy/io/micronaut/build/docs/CreateReleasesDropdownTaskSpec.groovy
This protects against build failures such as:
https://github.com/micronaut-projects/micronaut-liquibase/actions/runs/3749152160/jobs/6367308330
```
Server returned HTTP response code: 403 for URL: https://api.github.com/repos/micronaut-projects/micronaut-liquibase/tags
```
=> fix: handle CreateReleaseDropdown HTTP error

src/main/groovy/io/micronaut/build/MicronautDocsPlugin.groovy
see: https://github.com/micronaut-projects/micronaut-build/pull/454#issuecomment-1361695918
=> build: don't cache if fetching versions failed

build.gradle, src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy, src/main/groovy/io/micronaut/build/compat/MicronautBinaryCompatibilityPlugin.java, src/main/groovy/io/micronaut/build/docs/AggregatedJavadocParticipantPlugin.java, src/main/java/io/micronaut/build/MicronautQualityChecksParticipantPlugin.java, src/main/java/io/micronaut/build/compat/FindBaselineTask.java, src/main/java/io/micronaut/build/compat/VersionModel.java
The nohttp plugin isn't compatible with Gradle 8 and provides little value now that Gradle disables http by default.
=> Remove nohttp plugin

src/main/groovy/io/micronaut/build/docs/CreateReleasesDropdownTask.java, src/main/java/io/micronaut/build/compat/FindBaselineTask.java, src/main/java/io/micronaut/build/utils/GithubApiUtils.java, src/test/groovy/io/micronaut/build/utils/GithubApiUtilsSpec.groovy
And add logging of GitHub API errors.
=> Cache GitHub versions json in create dropdown task

src/main/java/io/micronaut/build/MicronautQualityChecksParticipantPlugin.java
This commit disables Jacoco by default for local builds. Jacoco will only be enabled on CI, but it can be enabled locally by setting the system property `micronaut.jacoco.enabled` to true (or the Gradle property of the same name).
=> Disable Jacoco on local builds

src/main/groovy/io/micronaut/build/MicronautDependencyResolutionConfigurationPlugin.java
When we switched the workflows to use the Gradle GitHub action, it enabled caching of the dependency cache. However, this causes an issue since by default snapshots are cached for 24 hours, and we don't want this to happen on CI.
This commit changes the configuration so that snapshots (and changing versions) aren't cached anymore on CI.
=> Disable caching of dynamic dependencies on CI

build.gradle, settings.gradle, src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy
This PR backports the Groovydoc task fix from #553
=> Backport Groovydoc fixes

src/functionalTest/groovy/io/micronaut/build/catalogs/BomGenerationFunctionalTest.groovy, src/main/groovy/io/micronaut/build/MicronautBomPlugin.java
Fixes https://github.com/micronaut-projects/micronaut-platform/issues/1169
=> Inline version properties in POM file

src/main/java/io/micronaut/build/MicronautGradleEnterprisePlugin.java
Migrated gradle remote cache to the gradleEnterprise connector and with that to access key authentication.
=> Migrated gradle remote cache to access key authentication 

src/functionalTest/groovy/io/micronaut/build/ReleasesDropdownFunctionalTest.groovy, src/main/groovy/io/micronaut/build/MicronautDocsPlugin.groovy, src/main/groovy/io/micronaut/build/docs/CreateReleasesDropdownTask.java
This task is currently broken. There is a discussion regarding removal of the dropdown here: https://github.com/micronaut-projects/micronaut-docs/issues/148
=> Remove release dropdown

src/main/groovy/io/micronaut/build/pom/PomChecker.groovy
This should help with https://github.com/micronaut-projects/micronaut-tracing/pull/640
=> Add suggestions to BOM checker

gradle/wrapper/gradle-wrapper.properties, src/main/java/io/micronaut/build/MicronautQualityReportingAggregatorPlugin.java
See https://docs.gradle.org/current/userguide/upgrading_version_8.html#changes_to_test_report_aggregation_and_jacoco_aggregation
Fixes #753
=> Fix compatiblity with Gradle 8.13

src/main/groovy/io/micronaut/build/compat/MicronautBinaryCompatibilityPlugin.java
In previous releases of Gradle (8.x) we were using the root project configurations container to create detached configurations, so that when we resolve a previous version of the current project, it would download it like any other external dependency. This worked but trigerred a deprecation warning for Gradle 9 saying that the resolution was done from another context, which would break in 9.
Unfortunately, there is no way to fix this, apparently, using public APIs. Therefore, I remembered that years ago I had introduced an API to get truly isolated resolvers. This API was hidden, so now it's internal, but it does exactly what we need.
This fixes the error we see for example at https://github.com/micronaut-projects/micronaut-test-resources/actions/runs/17290579530/job/49076754922?pr=900#ste …
=> Fix binary compatibility checks
