src/main/groovy/io/micronaut/build/MicronautDocsPlugin.groovy
Close: https://github.com/micronaut-projects/micronaut-core/issues/3062
I tested this by publishing to Maven Local and tyring the snapshot version in a project and the individual pages get deleted.
=> fix: delete individual pages

src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy
Fixes #68.
Tested locally with `micronaut-gcp-common`. Without this PR:
```xml
1   │ <?xml version="1.0" encoding="UTF-8"?>
2   │ <project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.
│ w3.org/2001/XMLSchema-instance">
3   │   
4   │   
5   │   
6   │   
7   │   
8   │   <modelVersion>4.0.0</modelVersion>
9   │   <groupId>io.micronaut.gcp</groupId>
10   │   <artifactId>micronaut-gcp-common</artifactId>
11   │   <version>3.3.1.BUILD-SNAPSHOT</version>
12   │   <dependencyManagement>
13   │     <dependencies>
14   │       <dependency>
15   │         <groupId>io.micronaut</groupId>
16   │         <artifactId>micronaut-bom</artifactId>
17   │         <version>2.1.3</version> …
```
=> Have only a `compileOnly` dependency of the Micronaut BOM.

src/main/groovy/io/micronaut/build/MicronautDocsPlugin.groovy
Currently classes from all projects are always included in javadoc regardless of `skipDocumentation` property
=> Honour skipDocumentation when building all javadoc

src/main/groovy/io/micronaut/build/MicronautPublishingPlugin.groovy
Otherwise, there are errors such as:
```
Execution failed for task ':data-bom:generateMetadataFileForMavenPublication'.
> Configuration with name 'runtimeClasspath' not found.
```
=> Do not enforce resolved versions for bom modules

src/main/groovy/io/micronaut/build/MicronautDocsPlugin.groovy
Fixes the issue mentioned [here](https://github.com/micronaut-projects/micronaut-docs/issues/23)
command to fetch branch name: `git rev-parse --abbrev-ref HEAD` returns a trialing newline character after branch name.
=> Fix trailing new line characters in github branch name

src/main/groovy/io/micronaut/build/MicronautPublishingPlugin.groovy, src/main/java/io/micronaut/build/catalogs/MicronautVersionCatalogUpdatePlugin.java
This PR fixes a couple of issues:
1. the local publication repository (in the "build" directory) should have used the root project build directory instead of each subproject directory
2. the "dependencyUpdates" task is called from some CI jobs, but it was missing if the new version catalog dependency updates plugin was applied instead of the old one
=> Minor fixes to the publishing and catalog plugins

src/main/java/io/micronaut/build/catalogs/tasks/VersionCatalogUpdate.java
Following a conversation with @ilopmar a new pattern will be introduced in our version catalog, where we actually want to use a dependency version from another BOM, so we don't want to define the version in our catalog, for internal use.
This commit fixes dependency upgrades whenever a version is empty, to support patterns like:
```toml
my-lib = { module = "foo:bar", version = "" }
```
In this case the version wouldn't be updated since we want to keep it empty.
=> Fix catalog update task to support empty versions

build.gradle, src/main/java/io/micronaut/build/MicronautSharedSettingsPlugin.java
This plugin must be applied on the `settings.gradle` file itself. For now, it only configures the Gradle Enterprise extension, but
it can be used to do much more, including enabling version catalogs, etc...
=> Introduce a shared settings plugin

build.gradle, src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy, src/main/groovy/io/micronaut/build/MicronautBuildExtension.groovy, src/main/java/io/micronaut/build/BuildEnvironment.java, src/test/groovy/io/micronaut/build/MicronautBuildExtensionSpec.groovy
This commit fixes the Gradle 8 deprecation warnings by upgrading to
the latest nohttp plugin version and using the required property
for reports instead of "enabled".
In order to make future upgrades easier, it also introduces the
notion of "build environment" in the Micronaut build extension.
For now the build environment is limited to telling if it runs
within a GitHub action or not.
=> Fix Gradle 8 deprecation warnings

build.gradle, src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy, src/main/groovy/io/micronaut/build/MicronautDependencyUpdatesPlugin.groovy, src/main/groovy/io/micronaut/build/MicronautDocsPlugin.groovy, src/main/groovy/io/micronaut/build/MicronautPublishingPlugin.groovy, src/main/java/io/micronaut/build/BuildEnvironment.java
This commit updates the plugins to avoid the creation of tasks at configuration
time. This will make the build faster and should eventually help us getting
rid of the many afterEvaluates that bloat the build.
Unfortunately, some of those changes are potentially breaking so a compatibility
mode has been introduced, and some builds can run with the `-DstrictBuild` flag
to be stricter and avoid some configuration.
It also fixes some weird task dependencies, but there are probably many more of them.
=> Avoid eager creation of javadoc/sources tasks

src/main/groovy/io/micronaut/build/MicronautPublishingPlugin.groovy, src/main/java/io/micronaut/build/MicronautSharedSettingsPlugin.java
The MicronautPublishingPlugin was trying to apply the Nexus publishing
plugin to the root project if the Nexus environment variables (or
system properties) were set. Unfortunately, this causes issues because
the evaluation of the root project is done when this happen.
Instead, the plugin will now properly be applied to the root project
if the variables are set, but it's done in a correct place (via the
settings plugin to avoid having to apply more plugins to the root
project).
=> Fix nexus publishing plugin

build.gradle, src/main/groovy/io/micronaut/build/MicronautBasePlugin.groovy, src/main/groovy/io/micronaut/build/MicronautBomCheckerPlugin.groovy, src/main/groovy/io/micronaut/build/MicronautBomPlugin.java, src/main/groovy/io/micronaut/build/MicronautBuildExtensionPlugin.java, src/main/groovy/io/micronaut/build/MicronautDependencyUpdatesPlugin.groovy, src/main/groovy/io/micronaut/build/MicronautPublishingPlugin.groovy, src/main/groovy/io/micronaut/build/pom/MicronautBomExtension.java, src/main/groovy/io/micronaut/build/pom/PomChecker.groovy, src/main/groovy/io/micronaut/build/pom/VersionCatalogConverter.groovy
This commit introduces a couple of BOM plugins, which can be used in any
Micronaut project. The first one, `io.micronaut.internal.bom` is probably
the most interesting to all projects, since it allows the creation of a
BOM for a multi-project.
Instead of having each module define how a BOM is generated, this provides
a conventional way to do it, with an extension to customize the behavior.
A typical Micronaut BOM project would only need to do this:
```gradle
plugins {
id 'io.micronaut.build.internal.bom'
}
version projectVersion
group projectGroup
```
And this would:
- generate a BOM including all submodules, except well-known modules
(test-suite, bom, ...)
- generate a Gradle version catalog
In addition, if the module is using a Gradle version catalog, then the
BOM can include additional …
=> Introduce a BOM plugin

build.gradle, src/functionalTest/gradle-projects/test-aot-module/build.gradle, src/functionalTest/gradle-projects/test-aot-module/gradle.properties, src/functionalTest/gradle-projects/test-aot-module/settings.gradle, src/functionalTest/gradle-projects/test-aot-module/src/main/java/io/micronaut/myaot/MyAot.java, src/functionalTest/gradle-projects/test-aot-module/src/main/resources/META-INF/services/io.micronaut.aot.core.AOTCodeGenerator, src/functionalTest/gradle-projects/test-aot-module/src/test/groovy/io/micronaut/myaot/MyAotSpec.groovy, src/functionalTest/groovy/io/micronaut/build/AbstractFunctionalTest.groovy, src/functionalTest/groovy/io/micronaut/build/aot/AOTModuleFunctionalTest.groovy, src/main/groovy/io/micronaut/build/aot/MicronautAotModulePlugin.java, src/main/java/io/micronaut/build/aot/MicronautBuildAotExtension.java
This plugin makes it possible to build Micronaut AOT modules. A
Micronaut AOT module isn't a traditional Micronaut module: it will
not use injection, and needs to use a specific API. The plugin is
responsible for setting up the project in the correct way, and it
will automatically add the test fixtures from AOT.
This means that in a particular Micronaut repository, it is possible
to have a module which is an extension to AOT. The user would then
have to integrate the AOT module to the AOT classpath (via the Gradle
plugin for now) to benefit from the optimizations.
=> Introduce AOT module plugin

src/main/groovy/io/micronaut/build/MicronautBomPlugin.java
This commit fixes the project version substitution which missed the trailing `.version`.
=> BOM property version fix

src/main/groovy/io/micronaut/docs/BuildDependencyMacro.groovy, src/test/groovy/io/micronaut/docs/BuildDependencyMacroSpec.groovy
This is to fix a few misleading declarations in Micronaut's Guide, s.a.:
`runtime("io.netty:netty-transport-native-epoll:linux-x86_64")`
... which makes gradle handle `linux-x86_64` as a *version* instead of a *classifier*:
> Resource missing. [HTTP GET: https://jcenter.bintray.com/io/netty/netty-transport-native-epoll/linux-x86_64/netty-transport-native-epoll-linux-x86_64.pom]
The above should indeed be spelled:
`runtime("io.netty:netty-transport-native-epoll::linux-x86_64")`
(the actual version comes through Micronaut's BOM).
=> Fix position of classifier in gradle dependencies

src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy
As discussed with the Gradle team, generating reports is pretty cheap.
By having a different strategy to generate reports on CI and locally,
this prevents reusing build cache entries.
=> Always generate test reports

src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy, src/main/groovy/io/micronaut/build/MicronautBuildExtension.groovy, src/main/java/io/micronaut/build/MicronautCompileOptions.java
This commit enables _forked compilation_, which seems to improve
stability of builds, especially when changing annotation processors.
It is possible, on a per-project basis, to disable forked compilation
or change the default maximum memory per forked process.
=> Enable forked compilation by default

src/main/groovy/io/micronaut/build/MicronautBasePlugin.groovy, src/main/groovy/io/micronaut/build/MicronautDocsPlugin.groovy, src/main/groovy/io/micronaut/build/docs/AggregatedJavadocParticipantPlugin.java, src/main/groovy/io/micronaut/build/docs/JavadocAggregationUtils.java, src/main/groovy/io/micronaut/build/docs/JavadocAggregatorPlugin.java, src/main/groovy/io/micronaut/build/docs/PrepareJavadocAggregationTask.java
Before this commit, Javadoc aggregation was generated by accessing other
project's state directly. While being much simpler to write, this was
causing deprecation warnings in the build, regarding configurations
being resolved out of context.
The fix wasn't trivial to implement, because we need a generic fix
which supports includes and excludes. Therefore, the way the aggregation
works is now by applying a couple of plugins:
- on a module which needs to be aggregated, we apply a plugin which is
responsible for setting up a couple of outgoing configurations: one
for the _sources_ which need to participate in javadocs, and another
one with the _classpath_. This is `AggregatedJavadocParticipantPlugin`
- on the aggregating project, we also need a couple of configurations
which are this time …
=> Fix how aggregated javadocs are produced

src/main/java/io/micronaut/build/MicronautBuildSettingsExtension.java, src/main/java/io/micronaut/build/MicronautSharedSettingsPlugin.java
This commit introduces support for the Gradle remote build cache.
Remote cache is enabled by default, but can be disabled by configuration
or passing `-PremoteCache=false` to the build parameters.
- Pushing to the cache is only enabled on CI.
- Reading from the cache is allowed with anonymous access
=> Add support for remote build cache

build.gradle, src/main/groovy/io/micronaut/build/MicronautDependencyUpdatesPlugin.groovy
This commit fixes the "useLatestVersions" task which was broken in 2 cases:
- for most projects, it wouldn't run the `dependencyUpdates` task prior to execution
- for projects using version catalogs, the version catalog update plugin should be used instead
-
=> Fix useLatestVersions

build.gradle, gradle.properties, settings.gradle, src/main/groovy/io/micronaut/build/MicronautBaseModulePlugin.groovy, src/main/groovy/io/micronaut/build/compat/AcceptanceHelper.groovy, src/main/groovy/io/micronaut/build/compat/AcceptedApiChange.java, src/main/groovy/io/micronaut/build/compat/AcceptedApiChangesParser.groovy, src/main/groovy/io/micronaut/build/compat/AcceptedApiChangesRule.java, src/main/groovy/io/micronaut/build/compat/BinaryCompatibibilityExtension.java, src/main/groovy/io/micronaut/build/compat/InternalAnnotationCollectorRule.java, src/main/groovy/io/micronaut/build/compat/InternalAnnotationPostProcessRule.java, src/main/groovy/io/micronaut/build/compat/InternalMicronautTypeRule.java, src/main/groovy/io/micronaut/build/compat/MicronautBinaryCompatibilityPlugin.java, src/main/java/io/micronaut/build/compat/FindBaselineTask.java, src/main/java/io/micronaut/build/compat/VersionModel.java, src/test/groovy/io/micronaut/build/compat/VersionModelTest.groovy
This PR adds a new feature to the build plugins: binary compatibility checks. It leverages the [JApiCmp Gradle Plugin](https://github.com/melix/japicmp-gradle-plugin). By default, all projects applying the `io.micronaut.build.internal.module` will automatically gain binary compatibility checks.
The checker will automatically perform verification against the latest release of a module. For this purpose, it makes use of the GitHub releases API to figure out the previous release. In case a module is a new module and that there's nothing to compare against, the binary check can be disabled by configuration:
```gradle
micronautBuild {
binaryCompatibility {
enabled = false
}
}
```
It is also possible to provide an explicit baseline, instead of checking against the previous release:
```gradle …
```
=> Add binary compatibility checks

build.gradle, src/main/java/io/micronaut/build/MicronautBuildSettingsPlugin.java, src/main/java/io/micronaut/build/MicronautGradleEnterprisePlugin.java, src/main/java/io/micronaut/build/MicronautSharedSettingsPlugin.java, src/main/java/io/micronaut/build/ProviderUtils.java
This commit extracts the Gradle Enterprise configuration into
its own plugin, so that it can be applied on projects which
only need support for Gradle Enterprise, but not publishing.
The plugin id is `io.micronaut.build.internal.gradle-enterprise`
=> Extract Gradle Enterprise configuration

src/main/groovy/io/micronaut/build/MicronautBomCheckerPlugin.groovy, src/main/groovy/io/micronaut/build/MicronautBomPlugin.java, src/main/groovy/io/micronaut/build/pom/BomSuppressions.java, src/main/groovy/io/micronaut/build/pom/CheckPomAction.java, src/main/groovy/io/micronaut/build/pom/MicronautBomExtension.java, src/main/groovy/io/micronaut/build/pom/PomChecker.groovy, src/main/groovy/io/micronaut/build/pom/PomDependency.java, src/main/groovy/io/micronaut/build/pom/PomDownloader.java, src/main/groovy/io/micronaut/build/pom/PomFile.java, src/main/groovy/io/micronaut/build/pom/PomFileAdapter.groovy, src/main/groovy/io/micronaut/build/pom/PomParser.groovy, src/main/groovy/io/micronaut/build/pom/PomValidation.java, src/main/java/io/micronaut/build/compat/VersionModel.java
This commit completely reworks how BOM validation works. Now we're validating
BOMs from the _generated BOM_, recursively. Any validation problem will
immediately fail the build, requiring explicit configuration to accept
problems. There are 2 ways to silence problems:
- using `micronautBom.suppressions.dependencies` to accept individual
problems on dependencies
- using `micronautBom.suppressions.bomAuthorizedGroupIds` for BOMs
which contain dependencies on artifacts belonging to different groups
Compared to the previous code, this one will perform _recursive_
validation, visiting transitive BOMS which are included.
Fixes #286
=> Rework BOM validation

src/main/groovy/io/micronaut/docs/BuildDependencyMacro.groovy, src/test/groovy/io/micronaut/docs/BuildDependencyMacroSpec.groovy
Fixes #293
I also removed a `break` statement that I couldn't see as serving any purpose
=> Map the runtime scope to runtimeOnly for doc snippets

src/main/groovy/io/micronaut/build/MicronautBomPlugin.java, src/main/groovy/io/micronaut/build/pom/MicronautBomExtension.java, src/main/groovy/io/micronaut/build/pom/PomChecker.groovy
Before this change, the only way to exclude a project from the BOM
was to use the `excludeXXX` methods on `micronautBom` extension.
With this change, by default, we will now only include projects
which apply the `publishing` plugin, that is to say the projects
which are supposed to be published on Maven Central.
In case this causes problems, it is possible to disable inference
by setting the appropriate property:
```gradle
micronautBom {
inferProjectsToInclude = false
}
```
The plugin will now also show which projects are included
when creating the POM file.
This should reduce problems like https://github.com/micronaut-projects/micronaut-data/pull/1404.
I have tested this on `micronaut-data`, which configuration for the BOM can now be reduced to:
```gradle
plugins {
id …
```
=> Improve how we decide to include a project in BOM

src/main/java/io/micronaut/build/catalogs/MicronautVersionCatalogUpdatePlugin.java, src/main/java/io/micronaut/build/catalogs/tasks/VersionCatalogUpdate.java
The use of the `copy` task with the same input and output directory
was causing the `gradle` directory to be emptied, instead of
creating a PR which properly upgrades dependencies.
This for example fixes incorrect PRs like https://github.com/micronaut-projects/micronaut-aot/pull/62
=> Fix how catalogs are updated on CI

build.gradle, src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy, src/main/java/io/micronaut/build/MicronautGradleEnterprisePlugin.java
This commit adds support for preditive test selection, reducing feedback
times when enabled. Predictive selection is enabled by default for local
builds, unless the `PREDICTIVE_TEST_SELECTION` environment variable or
`predictiveTestSelection` system property is set to `false`.
On CI this would depend on whether the above environment variable or
system property is set to `true` for each workflow.
Tested on Micronaut Core: https://ge.micronaut.io/s/ziotydt2gwbna
As per @eriwen's recommendation, this should only be enabled on CI for pull requests. This means our build template workflows should probably set the `PREDICTIVE_TEST_SELECTION` if the branch is a PR (I'm not sure how to do this with GitHub actions configuration files).
=> Add support for predictive test selection

build.gradle, src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy
This fixes a bug which prevented test selection to work properly with JUnit 5.7.
We can now remove the constraint, which should avoid cache misses when a build
is executed on CI and that test selection is enabled locally.
FYI @leonard84
=> Upgrade test distribution plugin

src/functionalTest/gradle-projects/test-micronaut-module/gradle.properties, src/functionalTest/gradle-projects/test-micronaut-module/gradle/libs.versions.toml, src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy, src/main/groovy/io/micronaut/build/MicronautModulePlugin.groovy, src/main/groovy/io/micronaut/build/util/VersionHandling.java, src/main/java/io/micronaut/build/MicronautBuildSettingsExtension.java, src/main/java/io/micronaut/build/MicronautBuildSettingsPlugin.java
This commit improves how Micronaut versions are read, so that we can
consistently use version catalogs. Previously to this change, some
versions still had to be declared in `gradle.properties`, which was
inconsistent with the use of the version catalog for other dependencies.
With this change, it is possible to declare everything in the catalog,
including the special versions `micronaut`, `micronaut-docs`, `micronaut-test`,
`groovy` and `spock`.
This change in made in a compatible way: if the version is defined in the catalog
it will be fetched from it, otherwise it will get the old version from the
gradle properties file.
This is a pre-requisite to updating the project template to use version catalogs.
=> Improve version property lookup

src/main/java/io/micronaut/build/MicronautBuildSettingsExtension.java, src/main/java/io/micronaut/build/MicronautSharedSettingsPlugin.java, src/main/java/io/micronaut/build/util/VersionHandling.java
If a project uses a version catalog, the `micronautVersion` property isn't
exposed to build scripts anymore, which might be a problem for some plugins
(like the Micronaut application plugin) which need it to be set.
=> Expose `micronautVersion` property to build scripts

src/main/groovy/io/micronaut/build/MicronautBomPlugin.java, src/main/java/io/micronaut/build/util/VersionHandling.java, src/test/groovy/io/micronaut/build/util/VersionHandlingTest.groovy
Before this change, `micronaut-docs` was incorrectly mapped so
the property being looked for was `micronaut-docsVersion` instead
of `micronautDocsVersion`.
This fixes a weird dependency resolution error which was hidden behind a "repositories setup" problem: https://ge.micronaut.io/s/ferz7p7ktjevq/failure#1
The actual problem was a missing dependency version.
=> Fix mapping from catalog version alias to property name

src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy
This commit fixes `micronaut-build` application on `micronaut-core`:
there was a test which verified if the `micronautVersion` property was
set, but since we automatically create this property now, this was
causing a dependency to be injected automatically when it shouldn't.
=> Fix `hasProperty(micronautVersion)`

src/main/groovy/io/micronaut/docs/BuildDependencyMacro.groovy
Context: https://github.com/micronaut-projects/micronaut-starter/pull/1215
We are using `developmentOnly` scope in the MicroStream module docs.
=> map developmentOnly to provided in maven

src/main/java/io/micronaut/build/MicronautQualityChecksParticipantPlugin.java
I am not quite sure why we have a dependency between checkstyle and
spotless. However since it's there, let's fix it so that it works
properly in case the spotless plugin isn't applied.
This commit fixes the case where the code quality plugin is applied
on a project which doesn't apply the spotless plugin, which might
be the case for "test projects" for example.
=> Fix spotless dependency

build.gradle, src/main/groovy/io/micronaut/build/compat/JavaBridgeAndSyntheticRule.java, src/main/groovy/io/micronaut/build/compat/MicronautBinaryCompatibilityPlugin.java, src/main/java/io/micronaut/build/compat/FindBaselineTask.java
This commit fixes a couple of issues with the binary compatibility
checks:
- first, the "baseline" task was cacheable, but didn't take into
account the actual contents of the JSON file returned by GH releases.
This means that if a release was made in between, we could compare
against an older baseline than expected.
- second, this commit introduces a rule to ignore Java bridge methods
and synthetic classes
The reason for the 2d change is that we moved from releasing with Java 8,
to releasing with Java 11 and targetting Java 8 bytecode. However the
Java 11 compiler may generate different synthetic code than the Java 8
one. So we simply ignore those internal implementation details.
=> Fix binary compatibility checks

src/main/java/io/micronaut/build/compat/FindBaselineTask.java
I believe we are being rate-limited on finding a baseline for jacpi.
This change adds Bearer authentication to the request if GITHUB_TOKEN is defined in the environment.
This will increase our rate limit
=> Authenticate with GitHub when fetching a baseline

src/main/groovy/io/micronaut/build/compat/MicronautBinaryCompatibilityPlugin.java
Because of the wrapping of the provider, the dependency isn't properly
tracked by Gradle.
=> Fix dependency on baseline task

src/main/groovy/io/micronaut/build/compat/MicronautBinaryCompatibilityPlugin.java
When adding a BOM to a module, you need to disable binary compatability for the first release
or it will fail to find the previous BOM in maven.
When it's disabled in the BOM module, we correctly disabled fetching the baseline
but we were not skipping fetching the POM.
=> bug: disabled binarycompat should skip checkVersionCatalogCompatibility

build.gradle, src/main/groovy/io/micronaut/build/DeprecatedTask.java, src/main/groovy/io/micronaut/build/MicronautDependencyUpdatesPlugin.groovy
We don't use that plugin anymore. In order to make sure workflows still work in case they are still using this task, a `DeprecatedTask` has been added, which warns to remove the use of the task.
=> Remove the dependency updates plugin

src/functionalTest/groovy/io/micronaut/build/PluginDefaultsFunctionalTest.groovy, src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy, src/main/groovy/io/micronaut/build/docs/JavadocAggregatorPlugin.java, src/main/java/io/micronaut/build/MicronautBuildExtension.java
This commit makes the build plugin configure Java 17 by default. It deprecates the use of `sourceCompatibility` and `targetCompatibility` on the `micronautBuild` extension, in favor of using Gradle's toolchain support instead.
If a project is not ready for Java 17, which is likely to happen for current Micronaut modules, it is possible to override the default Java version by setting the `micronautBuild.javaVersion` property.
If a project is _today_ using the `micronautBuild.sourceCompatibility` property (or `targetCompatibility`), then toolchain support isn't used, and a deprecation warning is issued during the build.
=> Default to Java 17

src/main/groovy/io/micronaut/build/MicronautPublishingPlugin.groovy
This commit adds the inclusion of the generated `pom.xml` file into the `META-INF/maven/group.id/artifact.id` directory of the published jars. While this file can be fetched externally, some vulnerability scanners actually look for this file.
It doesn't guarantee that users would use the exact same version of dependencies, but it is consistent with what Maven would do, for the better or worse.
=> Include a pom.xml file into the published jars

src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy
We had issues with Groovy 4, cgilib, Spock and Java 17
https://github.com/micronaut-projects/micronaut-kubernetes/pull/510\#issuecomment-1278775288
This pr switches cgilib to byte buddy, as cgilib is no longer maintained
=> Switch to byte buddy

src/main/groovy/io/micronaut/build/MicronautBasePlugin.groovy, src/main/groovy/io/micronaut/build/graalvm/NativeImagePropertiesExtension.java, src/main/groovy/io/micronaut/build/graalvm/NativeImageSupportPlugin.java, src/main/groovy/io/micronaut/build/graalvm/NativePropertiesWriter.java, src/test/groovy/io/micronaut/build/graalvm/NativeImageSupportPluginTest.groovy, src/test/groovy/io/micronaut/build/graalvm/NativePropertiesWriterTest.groovy
This commit introduces a new native image properties file generator. This will be useful for https://github.com/micronaut-projects/micronaut-core/issues/8073 since we want to avoid hardcoding the groupId and artifactId in `src/main/resources`. Using this task, projects which need to generate a native-image.properties file can activate generation via the `micronautBuildExtension`. For example:
```
micronautBuild {
nativeImageProperties {
features.add("my.AwesomeFeature")
}
}
```
=> Add native-image.properties generator

src/main/java/io/micronaut/build/MicronautBuildExtension.java
I tried versions after this, but then I started seeing
```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Property 'excludeScope' does not exist, please check the documentation
at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:227)
at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:194)
at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:123)
```
This was the latest version that supported enhanced instanceof, and still worked
See https://github.com/micronaut-projects/micronaut-session/pull/3/files#diff-7e845743b3275ae8a6a36524c32064120f1a55235372b55a5f8d2a6b685b919fR59
=> Update checkstyle to support Java17 enhanced instanceof

src/main/groovy/io/micronaut/build/pom/PomChecker.groovy
If the current POM file being checked is a Micronaut BOM, then we assume that we don't want to check that it should only "talk" about dependencies in the same group. Otherwise, we have many validation failures because basically all of our BOMs do this.
Only BOMs which are from other sources are verified, and need an explicit suppression of error.
=> Skip some checks if Micronaut BOM

gradle.properties, src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy, src/main/java/io/micronaut/build/BomSupport.java, src/main/java/io/micronaut/build/MicronautBuildSettingsExtension.java
Before this change, if a project used `importMicronautCatalog`, then the BOM which would be imported would be the Micronaut BOM, that is to say `io.micronaut:micronaut-bom`. With this change, if the target Micronaut version is 4+, then we will import the core catalog instead.
It is possible for modules to import other catalogs (BOMs) in their own namespace. For example, imagine a project which wants to use the `core` dependencies as well as those from the `aws` project, then in the settings file you can write:
```gradle
micronautBuild {
// imports the "core" catalog as "mn"
importMicronautCatalog()
// imports the "aws" catalog as "mnAws"
importMicronautCatalogWithGAV("io.micronaut.aws:micronaut-aws-bom:3.9.3")
// alternatively, if the project uses a version catalog and declares
// the BOM …
```
=> Use the new core BOM instead of the platform BOM

src/functionalTest/groovy/io/micronaut/build/AbstractFunctionalTest.groovy, src/functionalTest/groovy/io/micronaut/build/PluginDefaultsFunctionalTest.groovy, src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy
This commit adds a sanity check, which compares the version of Micronaut that a module declares (e.g `micronautVersion=3.4.1`) with the version which is resolved.
If the resolved version has a different major or minor, then the build will fail.
=> Add a sanity check for the resolved Micronaut version

src/main/java/io/micronaut/build/MicronautBuildSettingsExtension.java
When using `importMicronautBom()`, we will now automatically import the Micronaut Core BOM as `mn`, but also the Micronaut Test BOM as `mnTest`, if the `micronautTest` version is defined, either in the version catalog or gradle.properties.
=> Automatically add `mnTest` catalog

src/main/java/io/micronaut/build/MicronautBuildExtension.java
Upgrade to checkstyle 10.5.0 so that we properly support Java 17.
Once merged and that we release a new version of the plugin, we will have to update the project template to use new rules.
=> Upgrade checkstyle

src/main/groovy/io/micronaut/build/MicronautDocsPlugin.groovy
Without this, generating docs simply fails
=> Fix doNotCacheIf

src/main/groovy/io/micronaut/build/MicronautDocsPlugin.groovy
Builds are still failing. Attempt to catch a more generic build.
=> catch a more generic exception

src/main/java/io/micronaut/build/utils/GithubApiUtils.java
https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#user-agent-required
> All API requests MUST include a valid User-Agent header. Requests with no User-Agent header will be rejected. We request that you use your GitHub username, or the name of your application, for the User-Agent header value. This allows us to contact you if there are problems.
It seems this may be the culprit why [we are still seeing a 403]( https://ge.micronaut.io/s/l2lhrfn7gzlck).
https://stackoverflow.com/questions/39907742/github-api-is-responding-with-a-403-when-using-requests-request-function
Default Github Actions Env. variables: https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
=> Populate user agent header for Github Requests

src/main/groovy/io/micronaut/build/pom/PomDownloader.java
When verifying that a BOM file only refers to dependencies which exist on remote repositories, we perform parallel verification of all artifacts in the dependency graph, in order to make verification faster.
However, it is possible that the same dependency appears multiple times in the graph, in which case we could try to download the same file concurrently, which is fine, but we would also try to copy the result into our local cache. This step could fail because another thread could be writing the same file.
In order to protect from this, we now make sure that concurrent requests for the same artifact are blocked.
This problem was accidentally discovered by @dstepanov .
=> Fix race condition when verifying BOM

src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy
This change the default behavior of the Gradle IDEA plugin, which by default download all sources for dependencies. It's enabled here in the original `IdeaModule` class:
https://github.com/gradle/gradle/blob/ed053faa4ef92bbb81d7c9bb49dd30a01080bb7c/subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/model/IdeaModule.java#L174
IDEA allows downloading sources on demand:
Disabling automatic downloading of all sources dramatically speeds up importing micronaut projects in IDEA, especially when the project updated quite a lot of dependencies, on top of that it requires less disk space. For thoose who is not frequent contributor to Micronaut projects this change is quite useful as it saves a lot of time during importing.
=> Disable automatic download all sources and javadocs.

build.gradle, src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy
This will re-activate predictive test selection which is now disabled because we use an outdated version of the plugin.
=> Upgrade GE plugin

build.gradle
This is a follow-up to #472 : the plugin is no longer required as this is bundled into the GE plugin.
=> Remove test retry plugin

build.gradle, src/main/java/io/micronaut/build/utils/GithubApiUtils.java, src/test/groovy/io/micronaut/build/utils/GithubApiUtilsSpec.groovy, src/test/resources/io.micronaut.build.utils/releases.json
This commit mocks the GitHub API in tests.
=> Mock GitHub API

src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy
This commit adds the ability to run tests on a specific JDK, by making the `java.vendor` an input to the test tasks. In order to reduce the impact on caching for other users, this is opt-in: it will require setting the `MICRONAUT_TEST_USE_VENDOR` environment variable to `true` in a workflow, in which case the tests will have the vendor as an additional input.
Important: this will only work for modules which apply the `io.micronaut.build.internal.common` plugin (which is the case for `io.micronaut.build.internal.base-module` and `io.micronaut.build.internal.module`), so it is likely that projects which also include test suites or benchmarks will have to do something similar if they want tests to be executed on a different JDK.
Fixes #494
=> Make it possible to run tests on specific JDK

README.md
jcenter is deprecated and I don't see anywhere in the code that adds this
=> Remove `jcenter()` from README

src/main/java/io/micronaut/build/MicronautBuildSettingsExtension.java
The build settings extension was using package protected methods, which means that it worked accidentally in Groovy build scripts, but not in Kotlin build scripts.
=> Fix build settings extension method visibility

src/main/java/io/micronaut/build/MicronautGradleEnterprisePlugin.java
When investigating flakiness, it's useful to see (at a glance) whether there's some commonality to the flaky builds.
This PR adds two tags to build scans.
The current jdk vendor taken from the system properties, and the current major Java version running the build.
The vendor is munged so non alphanumeric chars are replaced by underscores, ie: 'Azul Systems, Inc.' becomes 'Azul_Systems_Inc_'
=> Add java details as tags to the build scan

src/main/java/io/micronaut/build/MicronautBuildSettingsExtension.java, src/main/java/io/micronaut/build/MicronautSharedSettingsPlugin.java
This commit answers feedback from https://github.com/micronaut-projects/micronaut-acme/pull/279#issuecomment-1454054896 by making it possible to configure a list of project name prefixes and project path prefixes which should be ignored when renaming projects. It also adds the `:examples` project path prefix as ignored by default.
=> Add more options to configure standard project names

src/main/groovy/io/micronaut/build/aot/MicronautAotModulePlugin.java
Micronaut AOT 2.0.0 uses different capability coordinates for its test fixtures (consistenly with the main GAV coordinates). This commit adds support for the new capability.
@sdelamo this fixes the issue you've reported in https://github.com/micronaut-projects/micronaut-security/pull/1250#discussion_r1135003805
=> Fix AOT test fixtures coordinates

src/main/groovy/io/micronaut/build/MicronautDependencyResolutionConfigurationPlugin.java
We have seen releases failing when generating the javadocs. The reason is that there's conflict resolution happening between versions like `-M1` and `-SNAPSHOT`, where `-SNAPSHOT` wins. The consequence is that when we compute the javadoc classpath, we don't resolve project dependencies, but binaries, which miss the javadoc classpath variant.
In general, we should always prefer the project mdoules during conflict resolution: it is extremely unlikely we intentionally want to use a binary version of a project instead of the local version. Should this happen, the project can override the configuration by calling:
```
configurations.all {
resolutionStrategy {
failOnVersionConflict()
}
}
```
then explicitly handle conflict resolution. This
is arguably a bit painful, but there's no method
on …
=> Prefer project modules in conflict resolution

src/main/groovy/io/micronaut/build/MicronautBaseModulePlugin.groovy, src/main/groovy/io/micronaut/build/MicronautPublishingPlugin.java
The issue was discovered while working on converting a Maven build to a Micronaut Gradle build. One of the submodules had `doc` in its name, which caused it to skip publication, because our publishing plugin ignores all projects which name contains `doc`. When this happens, the `maven-publish` plugin wasn't applied, which caused a NPE:
https://ge.micronaut.io/s/nhcjp4oily63w
Even if the `maven-publish` plugin was explicitly added, then the registration would fail because the publication that we expect in checkPom is missing:
https://ge.micronaut.io/s/css5vunwizpsc
This commit fixes the bug by making sure that we only register the `checkPom` task if the maven publish plugin is applied.
=> Fix registration of checkPom task

build.gradle, gradle/libs.versions.toml, src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy
This plugin causes a resolution error failure when releasing. We switch to Gradle's groovydoc task instead, which shouldn't be a problem because we have almost no Groovy classes in the public API and it seems that Groovy docs are not published as part of the documentation we build in `docs`.
I will perform a new 6.3.x and 6.4.x release once this is merged, to unblock releases.
=> Remove the Groovydoc plugin use

src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy, src/main/java/io/micronaut/build/BuildEnvironment.java, src/main/java/io/micronaut/build/MicronautGradleEnterprisePlugin.java, src/test/groovy/io/micronaut/build/docs/CreateReleasesDropdownTaskSpec.groovy
This commit removes the GE configuration when the project group is not starting with `io.micronaut`, in which case we assume it's not an OSS project that we maintain, and therefore the GE configuration makes no sense.
=> Conditionally configure Gradle Enterprise

src/main/groovy/io/micronaut/build/MicronautBaseModulePlugin.groovy
If the base module plugin is applied via a convention plugin written in Kotlin, then the settings plugin warning message is triggerred during Kotlin accessors compilation, which is wrong. This commit fixes this by hardcoding the fact that we have the project name matching accessors compilation.
=> Fix incorrect warning with Kotlin DSL

src/main/groovy/io/micronaut/build/pom/VersionCatalogConverter.groovy
It is possible that a version alias is defined, but that its library isn't (e.g when importing BOMs). This causes some modules to be missing from the generated platform catalog.
Fixes https://github.com/micronaut-projects/micronaut-platform/issues/283
=> Do not add version aliases to known aliases

build.gradle, buildSrc/build.gradle, buildSrc/src/main/java/io/micronaut/internal/VersionsWriterTask.java, gradle/libs.versions.toml, src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy
Turns out these are needed for mocking. But instead of hardcoding the version in sources, they are now externalized in the catalog, which should give us the benefit of automated upgrades.
=> Restore objenesis/bytebuddy versions

src/main/groovy/io/micronaut/build/compat/MicronautBinaryCompatibilityPlugin.java
This fixes the issues with enabling binary compatibility checks on Micronaut Core (4.0.0):
- `findbaseLine` task is called even if the result of the execution is not needed, so we need to add an `onlyIf` condition
- the group id used in core is not yet migrated to standards, so japicmp was picking up the wrong group
To be backported to 5.4.x too.
=> More fixes for binary compatibility checks

src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy, src/main/java/io/micronaut/build/MicronautQualityChecksParticipantPlugin.java
The Sonar plugin (rightfully) assumes that options added to the compiler are instances of `String` because typed as a `List<String>`. Whenever compilerArgs.stream() is called, a class cast exception happens. However, build scripts often add arguments as GString in Groovy scripts.
To workaround this, we configure the compiler options by coercing to a `String` in an `afterEvaluate`.
=> Workaround for ClassCastException

src/main/java/io/micronaut/build/MicronautBuildSettingsExtension.java
This commit adds the ability to override the versions of dependencies declared in the catalogs that the build uses. For example, to override the `libs.managed.jackson` version, you can specify on the command-line:
`./gradlew :foo -Poverride.libs.managed.jackson=2.6.0`
Alternatively, it is possible to provide an override properties file:
`./gradlew foo -Poverride.file.libs=overrides.properties`
and the properties file must contain the following entry:
`managed.jackson=2.6.0`
in order to behave the same as the 1st example.
=> Provide option to override catalog versions from CLI

src/functionalTest/gradle-projects/test-bom-module/gradle/libs.versions.toml, src/functionalTest/groovy/io/micronaut/build/catalogs/BomGenerationFunctionalTest.groovy, src/main/groovy/io/micronaut/build/pom/VersionCatalogConverter.groovy
This commit fixes a problem where some aliases were not inlined in the platform BOM. For example, the `junit` BOM dependency is missing from the platform, despite `micronaut-test` including it.
The reason is that in `micronaut-test`, `junit` is a managed version, but for a BOM (alias `boms-...`). There were 2 ways to fix this problem:
1. include all versions from the embedded catalog during inlining. This worked, but with a drawback: only the version would be included (e.g `junit`), but no library would be present. Which means that the user would still have to figure out the coordinates of, say, the junit BOM.
2. the fix in this PR, which is to include `boms-` dependencies into the generated catalog. This works well and should be backwards compatible, since we're only adding new entries …
=> Fix BOMs not being inlined

build.gradle, gradle.properties, src/functionalTest/groovy/io/micronaut/build/PluginDefaultsFunctionalTest.groovy, src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy, src/main/java/io/micronaut/build/MicronautBuildExtension.java
Defaults to the JavaVersion.current() that is running the build
=> Allow configuration of JDK to execute tests under

src/main/groovy/io/micronaut/build/compat/AbstractBinaryCompatibilityExtension.java, src/main/groovy/io/micronaut/build/compat/BinaryCompatibibilityExtension.java, src/main/groovy/io/micronaut/build/compat/MicronautBinaryCompatibilityPlugin.java, src/test/groovy/io/micronaut/build/compat/BinaryCompatibilityExtensionTest.groovy
Often when a new module is added to a project, we need to disable binary compatibility checks for that module, because there's no previous release yet. To do this, developers often chose the easy way, which is to set `enabled = false` to the binary compatibility extension.
However, it is easy to forget to re-enable binary compatibility checks after a release. This PR adds a new method to the binary compatibility extension to express the fact that binary checks should be enabled once release X is done.
For example, instead of writing:
```java
micronautBuild {
binaryCompatibility {
String v = projectVersion - '-SNAPSHOT'
def (int major, int minor, int patch) = (v.split(/[.]/) as List).collect { Integer.parseInt(it) }
enabled = major > 2 || (major == 2 && minor > 2) || (major == 2 && minor …
```
=> Improve binary compatiblity activation

src/main/groovy/io/micronaut/build/compat/MicronautBinaryCompatibilityPlugin.java
Fixed caching for JapiCmp tasks which was caused by an absolute path.
This was visible in most (if not all) micronaut project, such as with [micronaut-data](https://ge.solutions-team.gradle.com/c/prvolmj2n4zwc/nj6vniinu4vvw/task-inputs?cacheability=cacheable,overlapping-outputs,validation-failure), where we see there's a difference in richReport.rules property. I've narrowed it down to an absolute path, after fixing which we get all the JapiCmp tasks [FROM-CACHE](https://ge.solutions-team.gradle.com/s/ve4s7gnwbe6zc/timeline?hide-timeline&type=me.champeau.gradle.japicmp.JapicmpTask).
=> Fixed caching for JapiCmp tasks which was caused by an absolute path.

build.gradle, src/functionalTest/gradle-projects/test-micronaut-module/subproject1/src/main/java/io/micronaut/subproject1/GenericConfig.java, src/functionalTest/gradle-projects/test-micronaut-module/subproject1/src/main/java/io/micronaut/subproject1/NormalConfig.java, src/functionalTest/groovy/io/micronaut/build/docs/ConfigPropertiesTest.groovy, src/main/java/io/micronaut/build/docs/props/JavaDocAtValueReplacementTask.java
When we specify a value (for example as a default), this task searches for this value and replaces it in the docs.
This wasn't working for generics as it relied on a space after the class name.
[Spotted in this class in our EclipseStore module](https://github.com/micronaut-projects/micronaut-eclipsestore/blob/add-caching/eclipsestore-cache/src/main/java/io/micronaut/eclipsestore/cache/EclipseStoreCacheConfigurationProperties.java)
=> fix: JavaDocAtValueReplacementTask and generic classes

src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy
We only want to define the Groovy version in core, and not in every module.
Currently, the internal plugins look for the groovy version in the module catalog, or properties.
This PR extends where we look for a Groovy version, so it will check the local catalog, and then the micronaut-core catalog for the version (and then the properties if not found in either)
=> Allow Groovy version to be from micronaut-core

build.gradle, src/functionalTest/groovy/io/micronaut/build/catalogs/VersionCatalogUpdateFunctionalTest.groovy, src/functionalTest/resources/io/micronaut/build/catalogs/VersionCatalogUpdateFunctionalTest/initial-7.versions.toml, src/functionalTest/resources/io/micronaut/build/catalogs/VersionCatalogUpdateFunctionalTest/updated-7.versions.toml, src/functionalTest/resources/repository/awesome/lib/awesome/3.0.7/awesome-3.0.7.pom, src/main/java/io/micronaut/build/catalogs/MicronautVersionCatalogUpdatePlugin.java, src/main/java/io/micronaut/build/catalogs/tasks/VersionCatalogUpdate.java
For each module, it is now possible to exclude some versions from upgrades, for example:
```gradle
tasks.named("updateVersionCatalogs") {
rejectedVersionsPerModule['awesome.lib:awesome'] = '3[.]0.[8-9]'
}
```
=> Add ability to reject versions by regular expression

build.gradle, gradle.properties, gradle/libs.versions.toml, settings.gradle, src/main/java/io/micronaut/build/MicronautDevelocityPlugin.java, src/main/java/io/micronaut/build/MicronautGradleEnterprisePlugin.java, src/main/java/io/micronaut/build/MicronautSharedSettingsPlugin.java
Our builds currently result in walls of Develocity deprecation warnings. This PR upgrades our builds to latest Develocity plugin. It also adds a property which can be set in `gradle.properties` to disable the plugin altogether.
In addition, this ugprades the nexus plugin to avoid build deprecations.
Given that it's a potential breaking change, I'm upgrading the major version to 7.0.
=> Upgrade to Develocity plugin

src/main/template/js/multi-language-sample.js
When a user views the documentation and clicks on a multi-lang snippet to view a specific language, we store that language in local-storage
So when they go to view another documentation doc, we remember what the language was, and select that one.
So someone who had selected Kotlin, sees Kotlin snippets when they go back later.
This had a bug in it. Sometimes when we add a multi-lang snippet we may only have a selection of languages covered in the tested source code. The issue is that when someone who has selected Kotlin previously lands on a page with a missing Kotlin snippet, they see no snippet as all are hidden.
See https://github.com/micronaut-projects/micronaut-data/issues/2896 for example
This PR introduces a new method which checks if a snippet group is all hidden, and if it is, it …
=> Fix documentation when default language is unavailable

src/main/groovy/io/micronaut/build/MicronautBasePlugin.groovy, src/main/java/io/micronaut/build/catalogs/tasks/VersionCatalogUpdate.java
This commit fixes an issue with version updates: when a custom implementation accepts a version, we should interrupt the loop otherwise it becomes possible for a lower version to be selected.
=> Fix multiple versions potentially accepted

build.gradle, gradle.properties, gradle/libs.versions.toml, src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy, src/main/java/io/micronaut/build/MicronautBuildSettingsExtension.java, src/main/java/io/micronaut/build/MicronautBuildSettingsPlugin.java, src/main/java/io/micronaut/build/utils/IncludedBuildSupport.java
This commit adds support for including source dependencies in our builds. This should dramatically simplify development of modules which require changes to upstream projects. Typically, a project may need changes to Micronaut Core, but you don't want to release a new version of Micronaut Core just to test these changes. Using source dependencies, this is now possible.
=> Integrate with includgit plugin

src/main/groovy/io/micronaut/build/MicronautPublishingPlugin.java, src/main/java/io/micronaut/build/MicronautSharedSettingsPlugin.java, src/main/java/io/micronaut/build/utils/IncludedBuildSupport.java, src/main/java/io/micronaut/build/utils/ProviderUtils.java
This commit adds support for a special use case, which is currently only used in the Micronaut Fuzzing project, which is to publish a module which is an included build of a Micronaut repository. This module is also a Gradle plugin, which requires special setup. Therefore, this commit only makes sure that this use case is working.
It also fixes an issue with the "useDevelopmentVersion" code which failed if the `checkouts` directory wasn't created in advance.
=> Support publishing of an included build
